# Generated by Django 4.1.7 on 2023-03-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=50)),
                ('check_type', models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=7)),
                ('point_id', models.IntegerField()),
            ],
        ),
    ]
