# Generated by Django 4.1.7 on 2023-03-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=7)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('new', 'New'), ('rendered', 'Rendered'), ('printed', 'Printed')], max_length=8)),
                ('pdf_file', models.FileField(upload_to='')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='printers.printer')),
            ],
        ),
    ]
